config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "courses#index"
  resources :courses, param: :url
  resources :categories
  resources :admins, path: "/427liHsinPractice", only: [:index] do
    collection do
      post :become_admin
      post :cancel_admin
    end
  end

  # 搭配gem Grape 實現 api
  mount CourseStore::API => '/'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses

  # validation
  validates :name, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :category, :optional => true
  has_many :purchase_records

  # validation
  validates :topic, :content, :category_id, presence: true

  validates :price, presence: true, numericality: {
    greater_than_or_equal_to: 0
  }
  validate :price_is_valid_decimal_precision
  
  CURRENCY = %w(TWD USD JPY GBP EUR AUD HKD MOP MYR BEF CAD FRF ITL PHP DEM CHF SEK NZD SGD ESP DKK INR NOK NLG FIM SAR THB IDR ZAR ATS IEP MXN PLN CZK TRY HUF VND CNY)
  validates :currency, presence: true, inclusion: { in: CURRENCY }

  validates :validity_period, presence: true, numericality: {
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 31,
    only_integer: true
  }
  validates :is_available, inclusion: { in: [true, false] }, exclusion: { in: [nil] }

  validates :url, presence: true, uniqueness: true, format: {    
    with: /\A[a-z0-9\-]+\z/,
    message: "限小寫英數字及橫線" 
  }

  def to_param
    url
  end

  private
  
  def price_is_valid_decimal_precision 
    if price.to_f != price.to_f.round(2) 
     errors.add(:price, " should only be two digits at most after the decimal point.") 
    end 
  end 

end

app/models/purchase_record.rb
class PurchaseRecord < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :purchase_records
  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def become_admin
    current_user.update_attribute :admin, true
    redirect_to admins_path, notice: "您成為管理員了。"
  end

  def cancel_admin
    current_user.update_attribute :admin, false
    redirect_to admins_path, notice: "您現在不是管理員了。"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private
  def record_not_found  
    render file: 'public/404.html', layout: false, status: 404
  end

  def authenticate_admin
    unless current_user.try(:admin?)
      flash[:alert] = "操作不允許。"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories= Category.order(id: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, notice: "類型新增成功!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: "類型更新成功!"
    else
      render :edit
    end
  end

  def destroy
    @category.destroy

    redirect_to categories_path, notice: "類型已刪除!"
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_course, only: [:edit, :update, :destroy, :show]

  def index
    @courses = Course.includes(:category).order(updated_at: :desc)
  end

  def show
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to courses_path, notice: "課程新增成功!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to courses_path, notice: "課程更新成功!"
    else
      render :edit
    end
  end

  def destroy
    @course.destroy

    redirect_to courses_path, notice: "課程已刪除!"
  end

  private
  def set_course
    @course = Course.includes(:category).find_by!(url: params[:url])
  end

  def course_params
    params.require(:course).permit(:topic, :price, :currency, :is_available, :url, :content, :validity_period, :category_id)
  end
end

app/controllers/purchase_records_controller.rb
class PurchaseRecordsController < ApplicationController
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper

  def diplay_is_available(course)
    course.is_available ? "上架中" : "未上架"
  end

  def display_course_currency(currency)
    case currency
      when "TWD"
        "新台幣(TWD)"
      when "USD"
        "美元(USD)"
      when "JPY"
        "日幣(JPY)"
      when "GBP"
        "英鎊(GBP)"
      when "EUR"
        "歐元(EUR)"
      when "AUD"
        "澳幣(AUD)"
      when "HKD"
        "港幣(HKD)"
      when "MOP"
        "澳門幣(MOP)"
      when "MYR"
        "馬來西亞林吉特 (MYR)"
      when "BEF"
        "比利時法郎(BEF)"
      when "CAD"
        "加幣(CAD)"
      when "FRF"
        "法國法郎(FRF)"
      when "ITL"
        "義大利里拉(ITL)"
      when "PHP"
        "菲律賓比索(PHP)"
      when "DEM"
        "德國馬克(DEM)"
      when "CHF"
        "瑞士法郎(CHF)"
      when "SEK"
        "瑞典克郎(SEK)"
      when "NZD"
        "紐西蘭幣(NZD)"
      when "SGD"
        "新加坡幣(SGD)"
      when "ESP"
        "西班牙比塞塔(ESP)"
      when "DKK"
        "丹麥克郎(DKK)"
      when "INR"
        "印度盧比(INR)"
      when "NOK"
        "挪威克郎(NOK)"
      when "NLG"
        "荷蘭盾(NLG)"
      when "FIM"
        "芬蘭馬克(FIM)"
      when "SAR"
        "沙烏地里亞爾(SAR)"
      when "THB"
        "銖(THB)"
      when "IDR"
        "印尼盧比(IDR)"
      when "ZAR"
        "蘭特(ZAR)"
      when "ATS"
        "先令(ATS)"
      when "IEP"
        "愛爾蘭鎊(IEP)"
      when "MXN"
        "墨西哥比索(MXN)"
      when "PLN"
        "茲羅提(PLN)"
      when "CZK"
        "捷克克郎(CZK)"
      when "TRY"
        "新土耳其里拉(TRY)"
      when "HUF"
        "富林特(HUF)"
      when "VND"
        "越南盾(VND)"
      else "CNY"
        "元人民幣(CNY)"
    end
  end

end

app/helpers/purchase_records_helper.rb
module PurchaseRecordsHelper
end

app/views/admins/index.html.erb
<h1>改變身份</h1>

<% if current_user.admin? %>
<p> 您現在的身份是管理員，可以對課程進行操作。</p>
  <%= link_to '取消管理員身份', cancel_admin_admins_path, method: 'post' %>
<% else %> 
<p> 您現在的身份是一般的使用者。</p>
  <%= link_to '我要成為管理員',  become_admin_admins_path, method: 'post' %>
<% end  %>
</br>
</br>
</br>


<%= link_to "返回上頁", :back %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |form| %>

  <div class="mb-3">
    <%= form.label :name, '類型主題' %></br>
    <%= form.text_field :name, class: "form-control", placeholder: "輸入想顯示的類型名稱" %>
  </div>

  <div class="actions">
    <%= form.submit  btn_label, class: "btn btn-success btn-sm" %>
  </div>

<% end %>

<% if @category.errors.any? %>
  <ul>
  <% @category.errors.full_messages.each do |msg| %>
    <li class="msg"><%= msg %></li>
  <% end %>
  </ul>
<% end %>

app/views/categories/edit.html.erb
<h1>編輯類型</h1>

<%= render 'form', category: @category, btn_label: '更新類型' %>

<%= link_to "返回上頁", :back %>

app/views/categories/index.html.erb
<h1>類型列表</h1>
<% if current_user.try(:admin?) %>
<%= link_to "新增類型", new_category_path, type: "button", class: "btn btn-outline-success btn-sm" %>
<% end  %>

<table>
  <tr>
    <td class="list_title">類型</td>
    <% if current_user.try(:admin?) %>
    <td>管理員動作</td>
    <% end  %>
  </tr>
  <% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <% if current_user.try(:admin?) %>
    <td><%= link_to '編輯', edit_category_path(category.id) %></td>
    <td><%= link_to '刪除', category_path(category.id), method: 'delete', data: {confirm:"類型 #{category.name} 即將被刪除。所有#{category.name}類型的課程將會變成沒有類型，確定嗎？"} %></td>
    <% end  %>
  </tr>
  <% end %>
</table>

<%= link_to "返回課程列表", courses_path %>

app/views/categories/new.html.erb
<h1>新增類型</h1>

<%= render 'form', category: @category, btn_label: '新增類型' %>

<%= link_to "返回上頁", :back %>

app/views/courses/_form.html.erb
<% if @course.errors.any? %>
  <ul class="mb-3">
  <% @course.errors.full_messages.each do |msg| %>
    <li class="msg"><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for(@course) do |form| %>

  <div class="mb-2">
    <%= form.label :topic, '課程主題' %></br>
    <%= form.text_field :topic, class: "form-control form-control-sm" %>
  </div>

  <div class="mb-2">
    <%= form.label :price, '價格' %></br>
    <%= form.number_field :price, min:"0", step: ".01", class: "form-control form-control-sm" %>
    <p class="small_p">(價格取至小數點第二位)</p>
  </div>

  <div class="mb-2">
    <%= form.label :currency, '幣別' %></br>
    <%= form.select :currency, Course::CURRENCY.map{|c|[ display_course_currency(c), c] } %>
  </div>

  <div class="mb-2">
    <%= form.label :category_id, '類型' %></br>
    <%= form.select :category_id, Category.all.map{ |c| [c.name, c.id] }, include_blank: true %>
    <%= link_to "編輯類型", categories_path %>
  </div>

  <div>
    <%= form.label :url, '設定網址' %>
    <div class="input-group input-group-sm">
      <span class="input-group-text" id="basic-addon1">http://hidden-reef-83151.herokuapp.com/courses/</span>
      <%= form.text_field :url, class: "form-control",placeholder: "輸入網址" %>
    </div>
    
    <p class="small_p">(限小寫英數字及橫線)</p>
  </div>
  

  <div class="mb-2">
    <%= form.label :content, '課程描述' %></br>
    <%= form.text_area :content, class: "form-control form-control-sm" %>
  </div>

  <div class="mb-2">
    <%= form.label :validity_period, '課程效期(天)' %></br>
    <%= form.select :validity_period, [*1..31], include_blank: true %>
  </div>

  <div class="mb-2">
    <%= form.label :is_available, '是否上架' %></br>
    <%= form.select :is_available, [['上架', true], ['未上架', false]] %>
  </div>

  <div class="mb-3">
    <%= form.submit  btn_label, class: "btn btn-success btn-sm" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>編輯課程 <%= @course.topic %></h1>

<%= render 'form', course: @course, btn_label: '更新課程' %>

<%= link_to "返回上頁", :back %>

app/views/courses/index.html.erb
<h1>課程列表</h1>
<% if current_user.try(:admin?) %>
<%= link_to "新增課程", new_course_path, type: "button", class: "btn btn-outline-success btn-sm" %>
<% end  %>


<table>
<tr class="list_title">
  <td>課程主題</td>
  <td>價格</td>
  <td>幣別</td>
  <td><%= link_to "課程類型", categories_path %></td>
  <td>效期</td>
  <td>是否上架</td>

</tr>
<% @courses.each do |course| %>
<tr>
  <td><%= link_to course.topic, course_path(course.url) %></td>
  <td><%= course.price %></td>
  <td><%= display_course_currency(course.currency) %></td>
  <td><%= course.category.try(:name) %></td>
  <td><%= course.validity_period %>天</td>
  <td><%= diplay_is_available(course) %></td>
  <% if current_user.try(:admin?) %>
    <td><%= link_to '編輯', edit_course_path(course.url) %></td>
    <td><%= link_to '刪除', course_path(course.url), method: 'delete', data: {confirm:"課程 #{course.topic} 即將被刪除。確定嗎?"} %></td>
  <% end  %>
</tr>
<% end %>
</table>

app/views/courses/new.html.erb
<h1>新增課程</h1>

<%= render 'form', course: @course, btn_label: '新增課程' %>

<%= link_to "返回上頁", :back %>

app/views/courses/show.html.erb
  <h1><%= @course.topic %></h1>

  <ul>
    <li>課程類別：<%= @course.category.try(:name) %></li>
    <li>課程描述：<%= @course.content %></li>
    <li>課程售價：<%= @course.price %><%= @course.currency %></li>
    <li>課程狀態：<%= diplay_is_available(@course) %></li>
    <li>課程效期：<%= @course.validity_period %>天</li>
  </ul>

<%= link_to "返回上頁", :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>

  <body>
    <%= render 'shared/header' %>
  
    <div class="container">
    <%= yield %>
    </div>
    
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flash_message.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
<footer>
  <p>Made by Lihsin - <a href="https://github.com/Lihsin0427/project_online_course">GitHub</a><p>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-light" style="background-color: rgb(162, 194, 153);">
  <div class="header_wrap">
    <div>
      <% if user_signed_in? %>
        <%= link_to '登出', destroy_user_session_path, method: 'delete' %> | 
        <%= link_to '修改密碼', edit_user_registration_path %> | 
      <% else %>
        <%= link_to '登入', new_user_session_path %> |
        <%= link_to '註冊', new_user_registration_path %> | 
      <% end %>

      <%= link_to '首頁', root_path %>
    </div>

    <div class="identity">
      <% if user_signed_in? %>
        <% if current_user.try(:admin?) %>
          <p>管理員身份</p>
        <% else %>
          <p>一般使用者</p>
        <% end  %>
      <% end  %>
    </div>
  </div>
</nav>
<div class="message">
  <%= render 'shared/flash_message' if notice||alert %>
</div>